PythonVersion="3.9.0"
packagedir=".python_packages/lib/site-packages"
OperationId="|bjW2fOEPc3M=.af8940ab_"
SourceDirectoryInBuildContainer="/tmp/8d95dec895bc947"
PlatformName="python"
CompressDestinationDir="false"
